version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
      - image: node:6.11.5
    steps:
      - checkout
      - run:
          name: installing angular cli
          command: npm install -g @angular/cli
      - run:
          name: Npm Install
          command: npm install
