version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:
          - TERM: xterm
      - image: node:8.6.0

    working_directory: ~/app
    parallelism: 1
    steps:
      - run: npm install
      - run: npm run build
