version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:
          - TERM: xterm
      - image: node:8.6.0
      - image: mongo:3.4.4
      - image: mysql:5.7
      - image: circleci/php:5.6.30-apache-browsers
        environment:
          - MYSQL_ROOT_PASSWORD=java@123
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_HOST=127.0.0.1

    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
            - v1-npm-deps
      - run: apt-get install git
      - run: git clone https://github.com/nodeexcel/api_hr_recruitment
      - run: cd api_hr_recruitment/
      - run: npm install
      - run: npm rebuild node-sass --force
      - run: npm start &
      - run: cd ..
      - run: npm install
      - run: npm start &
      - run: sleep 60s
      - save_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm install cypress
      - run:
          name: Running E2E tests with JUnit reporter
          command: npm run test-junit
      - store_test_results:
          path: results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots