version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:

    working_directory: ~/app
    parallelism: 1
    steps:
      - run: ng serve --prod
