version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:
          - TERM: xterm
      - image: node:8.6.0

    steps:
      - checkout
      - run: npm install
      - run: ng build --prod
