version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
      - image: node:6.11.5
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
