version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
      - image: node:8.6.0

    working_directory: ~/recruit
    steps:
      - checkout:
          path: ~/recruit
      - run: npm run build
