version: 2
jobs:
  build:
    docker:
      - image: node:6.6.0
      - image: cypress/base:6
      - image: cypress/browsers:chrome62
    steps:
      - checkout
      - run: npm install
      - run: cypress run --browser chrome
