version: 2
jobs:
  build:
    docker:
      - image: node:8.6.0
      - image: cypress/base:8
    steps:
      - checkout
      - run: npm install
      - run: npm install -g cypress-cli
      - run: npm run cypress:open
