version: 2
jobs:
  build:
    docker:
      - image: node:8.6.0
    steps:
      - checkout
      - run:
          name: installing angular cli
          command: npm install -g @angular/cli
      - run:
          name: Npm Install
          command: npm install
